[package]
name = "search-utils"
version = "0.1.0"
authors = ["Colt Frederickson <coltfred@gmail.com>"]
edition = "2018"

[dependencies]
sha2 = "0.8.1"
voca_rs = "1.9.1"
regex = "1.3.4"
lazy_static = "1.4.0"
itertools = "0.8.2"
unidecode = "0.3.0"